---
title: "Github - Traits Dominant Rare Tree Species"
author: "Anonymous"
date: "2024-05-17"
output: html_document
---

###Load packages
```{r Packages}
library(datasets)
library(data.table)
library(readxl)
library(feather)
library(plyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
library(FD)
library(vegan)
library(ggrepel)
library(Rmisc)
library(mgcv)
library(BIOMASS)
library(stringr)
library(gmodels)
library(relaimpo)
library(writexl)
library(dplyr)

```
###Load GFBI data
```{r GFBI Data}
setwd("/Volumes/usys_ibz_cr_lab/")
GFBI <- read_feather("/Volumes/usys_ibz_cr_lab/GFBI_Data/tree_data/GFBI_fixed_plots.feather") #plots: 1184025
```

###Filter Data for 1)plotsize 2)measurement year 3)Forest age 4)Forest biome 5)DBH treshold 
```{r Filter Data}
### 1)Filter plotsize
GFBI$Plotsize <- 1/GFBI$tph
GFBI_Filter_Ps <- GFBI[which(GFBI$Plotsize > 0.02 & GFBI$Plotsize < 2),]
GFBI_Filter_Ps <- as.data.frame(GFBI_Filter_Ps)

#table(is.na(GFBI_Filter_Ps$Plotsize)) #No na values
table(is.infinite(GFBI_Filter_Ps$Plotsize)) #Throw infinite numbers out, as their plotsize is close or equal to zero
GFBI_Filter_PsInf <-GFBI_Filter_Ps[!is.infinite(GFBI_Filter_Ps$Plotsize),]
table(is.infinite(GFBI_Filter_PsInf$Plotsize)) #Check

#unique(GFBI_Filter_PsInf$plot_id) #plots: 1085705
#100-((1085705/1184025)*100) #Percentage of plots filtered out: 8.3%

### 2)Filter measurement year
GFBI_Filter_Yr <- GFBI_Filter_PsInf[which(GFBI_Filter_PsInf$year > 1989),]
#unique(GFBI_Filter_Yr$plot_id) #plots: 857315
#100-((857315/1085705)*100) #Percentage of plots filtered out: 21%

###Select one measurement per plot
GFBI_Filter_YrCheck <- GFBI_Filter_Yr %>% group_by(plot_id) %>% filter(year == max(year))

###3) Filter forest age
#Create coordinates for extraction Biome and Forest age info GEE
GFBI_plot <- GFBI_Filter_YrCheck %>% group_by(plot_id) %>% slice(1)
# TraitsGFBI_coordinates <- subset(GFBI_plot, select=c(lat, lon, plot_id))
# setwd("~/Documents/PhD projects/Traits Dominant Species")
# fwrite(TraitsGFBI_coordinates, file="Trait_coordinates_05-2021.csv") #Create coordinates to export to GEE

rm(GFBI_Filter_Ps, GFBI_Filter_PsInf) #Clean-up workspace

###Import and add GEE information
setwd("~/Documents/PhD projects/Traits Dominant Species/Traits03-05-2021")
GEE <- list.files("~/Documents/PhD projects/Traits Dominant Species/Traits03-05-2021") %>% map_df(~fread(.))
GEE <- as.data.frame(GEE)
GFBI_GEE <- left_join(GFBI_plot, GEE, by="plot_id")

setnames(GFBI_GEE, old=c("system:index"), new=c("systemindex"))
GFBI_GEE <- subset(GFBI_GEE, select=-c(.geo, random, systemindex, old_plot_id, Pixel_Lat, Pixel_Long))

GFBI_filter_Age <- subset(GFBI_GEE, GFAD_regrowthForestAge_Mean_downsampled50km > 25 | is.na(GFAD_regrowthForestAge_Mean_downsampled50km)) #Filter Forest age <25 yr uit, while keeping "NA"
#100-((846246/857315)*100) #Percentage of plots filtered out: 1.3%
#(11670/846246)*100 #Percentage old growth forest: 1.4%

###4) Filter forest biomes
GFBI_filter_Biome <- GFBI_filter_Age[which(GFBI_filter_Age$Resolve_Biome < 7), ]

###5) Filter DBH
GFBI_filter_DBH <- GFBI_Filter_YrCheck[which(GFBI_Filter_YrCheck$dbh >= 5), ] #Filter DBH <5cm uit

###Merge filtered plots and tree-level data
GFBI_join_Age <- semi_join(GFBI_filter_DBH, GFBI_filter_Biome, by="plot_id")

###Add biome information
Biome <- subset(GFBI_filter_Biome, select=c(plot_id, Resolve_Biome))
GFBI_Age_Biome <- left_join(GFBI_join_Age, Biome, by="plot_id")

setwd("~/Documents/PhD projects/Traits Dominant Species")
fwrite(GFBI_Age_Biome, file="GFBI_Age_Biome.csv")

rm(GFBI_filter_Age, GFBI_filter_Biome, Biome, GFBI_filter_DBH, GFBI_Filter_Yr, GFBI_plot, GFBI, GEE, GFBI_Filter_Ps, GFBI_GEE, GFBI_join_Age) #remove datasets

###Fig 1 information om temp and AI
GFBI_Age_Biome <- fread("~/Documents/PhD projects/Traits Dominant Species/GFBI_Age_Biome.csv")
Coordinates13092021 <- subset(GFBI_Age_Biome, select=c(lat, lon, plot_id))

setwd("~/Documents/PhD projects/Traits Dominant Species")
fwrite(Coordinates13092021, file = "Coordinates13092021.csv")

#Import and add GEE information
setwd("~/Documents/PhD projects/Traits Dominant Species/TraitsEnv_09-2021")
AI <- list.files("~/Documents/PhD projects/Traits Dominant Species/TraitsEnv_09-2021") %>% map_df(~fread(.)) %>% as.data.frame()
AI <- subset(AI, select=c(plot_id, Resolve_Biome, CGIAR_Aridity_Index, CHELSA_BIO_Annual_Mean_Temperature))
AI_Plot <- AI %>% group_by(plot_id) %>% slice(1)
AI_Plot <-  AI_Plot[complete.cases(AI_Plot), ]
AI_Plot$Resolve_Biome <- as.numeric(AI_Plot$Resolve_Biome)
Fig1_Env <- AI_Plot %>% group_by(Resolve_Biome) %>% dplyr::summarise(MeanTemp = (mean(CHELSA_BIO_Annual_Mean_Temperature))/10, MeanAI = (mean(CGIAR_Aridity_Index)*0.0001)) %>% as.data.frame()

```
###Standardise species names & select trees with available trait information
```{r Standardise species names}
###Standardize species names with tree plant list & GBIF
GFBI_Age_Biome <- fread("~/Documents/PhD projects/Traits Dominant Species/GFBI_Age_Biome.csv")
Species_names <- read_feather("/Volumes/usys_ibz_cr_lab/GFBI_Data/tree_data/BEST_MATCH_all_species_TPL.feather")

GFBI_Species <- left_join(GFBI_Age_Biome, Species_names, by="raw_name")

#Only keep species which are identified up to species level
GFBI_Species <- GFBI_Species[which(GFBI_Species$tax_level == "2"),] # 1.7% of trees is only identified up to genus level #100-(12907085/13133048)*100
setnames(GFBI_Species, old=c("accepted_bin", "Resolve_Biome"), new=c("species_name", "Biome"))
GFBI_Species <- subset(GFBI_Species, select=-c(raw_name, old_plot_id, match_source, tax_genus, tax_species, tax_level))

rm(GFBI_Age_Biome, PlotNr, Species_names)
#Only keep species with trait information available
setwd("~/Desktop")
Traits <- read_feather("~/Desktop/GFBI_fixed_plots_ALL_TRAITS_7_21.feather") 

#Select complete cases 10 traits
setnames(Traits, old = c("trait1055","trait1229","trait14","trait144", "trait145", "trait146", "trait15", "trait185", "trait21", "trait24", "trait26",  
                         "trait270", "trait281", "trait3106", "trait3110", "trait3117", "trait3120", "trait324", "trait4", "trait413", "trait44", "trait45",  
                         "trait46", "trait48", "trait54", "trait56", "trait6", "trait773", "trait80", "trait9"), 
         new = c("RootCN", "WoodN", "LeafN", "LeafLength", "LeafWidth", "LeafCN", "LeafP", "VcmaxDryMass", "StemDiameter", "BarkThickness", "SeedMass", 
                 "JmaxDryMass", "StemConduitDiameter", "Height", "LeafArea", "SLA", "LeafWaterMass", "CrownDiameter", "WoodDensity", "LeafChlorophyll", "LeafK", "StomatalConductance",
                 "LeafThickness", "LeafDensity", "LeafRespRate", "LeafNP", "RootDepth", "CrownHeight", "RootN", "RootShootRatio"))

TraitsSelection <- subset(Traits, select=c(Height, CrownDiameter, BarkThickness, WoodDensity, SLA, LeafN, LeafNP, StemConduitDiameter, RootDepth, SeedMass, obs_id))
rm(Traits)

TraitsSelect <- TraitsSelection[complete.cases(TraitsSelection),] #dim(TraitsSelection) #31215811 dim(TraitsSelect) #29938442

ObsID <- as.data.frame(TraitsSelect$obs_id)
setnames(ObsID, old="TraitsSelect$obs_id", new="obs_id")

GFBI_SpeciesCheck <- inner_join(GFBI_Species, ObsID, by="obs_id") #dim(GFBI_SpeciesCheck) #12816859 dim(GFBI_Species) #12907085

setwd("~/Documents/PhD projects/Traits Dominant Species")
fwrite(GFBI_SpeciesCheck, file="GFBI_SpeciesCheck_7-2021.csv")

```
###Identify Dominant and Rare species on plot level based on 6 species threshold
```{r Identify Dominant and Rare species on plot level}
setwd("~/Documents/PhD projects/2nd Chapter - Trait diversity")
GFBI_SpeciesCheck <- fread("~/Documents/PhD projects/2nd Chapter - Trait diversity/GFBI_SpeciesCheck_7-2021.csv") #plots: 1184025

library(stringr)
sum(str_detect(GFBI_SpeciesCheck$species_name, 'Cyathea')) #No tree ferns
sum(str_detect(GFBI_SpeciesCheck$species_name, 'Dicksonia')) #No tree ferns
sum(str_detect(GFBI_SpeciesCheck$species_name, 'Atalea')) #No palms

GFBI_SumS <- as.data.frame(GFBI_SpeciesCheck %>% group_by(plot_id) %>% mutate(SumS=as.numeric(n_distinct(species_name)))) #Sum of species per plot
GFBI_atleast6Sp <- GFBI_SumS[which(GFBI_SumS$SumS >= 6),]

###Select subset biomes
Select_Plots <- GFBI_atleast6Sp[which(GFBI_atleast6Sp$Biome < 4 | GFBI_atleast6Sp$Biome == 5 | GFBI_atleast6Sp$Biome == 6),]

Select_PlotsBiome4 <- GFBI_atleast6Sp[which(GFBI_atleast6Sp$Biome == 4),] #Select 10.000 plots within biome 4
Select_PlotsBiome4Subset <- subset(Select_PlotsBiome4, plot_id %in% sample(unique(Select_PlotsBiome4$plot_id), 10000)) 
fwrite(Select_PlotsBiome4Subset, file="PlotsBiome4Subset.csv")

#Select_PlotsBiome4Subset <- fread("~/Documents/PhD projects/Traits Dominant Species/PlotsBiome4Subset.csv")

Select_PlotsFinal <- rbind(Select_Plots, Select_PlotsBiome4Subset)
fwrite(Select_PlotsFinal, file="Subset_Traits_GFBI.csv")

Select_PlotsFinal$NrInd <- 1 #Add Nr of individuals
GFBI_Plot <- Select_PlotsFinal %>% group_by(plot_id) %>% mutate(SumS=n_distinct(species_name), SumIndPlot=sum(NrInd),
                                                                                PercInd=(NrInd/SumIndPlot)*100, SumPercInd=sum(PercInd)) #Nr of Species, Nr Ind perc and sum per plot
GFBI_Plot <- as.data.frame(GFBI_Plot)

GFBI_MeanInd <- GFBI_Plot %>% group_by(plot_id, species_name) %>% summarise(PercPerSpecies=sum(PercInd), SumS=mean(SumS)) 
GFBI_MeanInd <- as.data.frame(GFBI_MeanInd)

###Select plots, with only 10% or less rare species
GFBI_MeanIndFilter <- GFBI_MeanInd %>% group_by(plot_id) %>% filter(any(PercPerSpecies <= 10)) #Filter out plots with percentage higher than 10%

# GFBI_PlotSlice <- GFBI_Plot %>% group_by(plot_id) %>% slice(1) #1:2503 #2:1720 #3:182 #4:509506 #5:90000 #6:57684
# GFBI_MeanIndFilterSlice <- GFBI_MeanIndFilter %>% group_by(plot_id) %>% slice(1) #1:2051 #2:1157 #3:92 #4:265125 #5:43242 #6:12934 ###49% of dataset

GFBI_Div20 <- GFBI_MeanIndFilter[which(GFBI_MeanIndFilter$SumS >= 20),] #700 plots, 0.11%
GFBI_Div6 <- GFBI_MeanIndFilter[which(GFBI_MeanIndFilter$SumS < 20 & GFBI_MeanIndFilter$SumS >= 6),] #144592 plots, 45%
GFBI_Div5 <- GFBI_MeanIndFilter[which(GFBI_MeanIndFilter$SumS < 6),] #179309 plots, 55% plots less than 6 species #Erased plots by biome, 1:459 2:200 3:275 4:536070 5:120705 6:39393 
GFBI_DivMore6 <- GFBI_MeanIndFilter[which(GFBI_MeanIndFilter$SumS >= 6),] #145292 plots, 45% plots 6 or more species. Nr of plots by biome 1:1930   2:1110 3:20 4:131737 5:8931 6:1564

GFBI_Div20Dom <- GFBI_Div20 %>% group_by(plot_id) %>% arrange(desc(PercPerSpecies)) %>% slice_head(prop=0.1) #Sorts from large to small and takes top 10%
GFBI_Div20Dom$DominanceCategory <- "dominant"

GFBI_Div20Rare <- GFBI_Div20 %>% group_by(plot_id) %>% arrange(desc(PercPerSpecies)) %>% slice_tail(prop=0.1) #Sorts from large to small and takes bottom 10%
GFBI_Div20Rare$DominanceCategory <- "rare"

GFBI_Div6Dom <- GFBI_Div6 %>% group_by(plot_id) %>% arrange(desc(PercPerSpecies)) %>% slice_head(n = 2) #takes top 2 species
GFBI_Div6Dom$DominanceCategory <- "dominant"

GFBI_Div6Rare <- GFBI_Div6 %>% group_by(plot_id) %>% arrange(desc(PercPerSpecies)) %>% slice_tail(n = 2) #takes bottom 2 species
GFBI_Div6Rare$DominanceCategory <- "rare"

GFBI_DivDR <- rbind(GFBI_Div20Dom, GFBI_Div20Rare, GFBI_Div6Dom, GFBI_Div6Rare)
GFBI_DivDR <- subset(GFBI_DivDR, select = c("plot_id", "species_name", "DominanceCategory", "PercPerSpecies"))
GFBI_DivDR <- as.data.frame(GFBI_DivDR)

GFBI_PlotMore6 <- GFBI_Plot[which(GFBI_Plot$SumS >= 6),]
PlotDominantRare <- merge(x = GFBI_PlotMore6, y = GFBI_DivDR, by = c("plot_id", "species_name"), all.x = TRUE)
PlotDominantRare$DominanceCategory <- replace(PlotDominantRare$DominanceCategory, is.na(PlotDominantRare$DominanceCategory), "intermediate")
PlotDominantRare <- as.data.frame(PlotDominantRare)

fwrite(PlotDominantRare, file="DominantRare_Plot_8-2021.csv")
DominantRareSp_plotlevel <- fread("~/Documents/PhD projects/2nd Chapter - Trait diversity/DominantRare_Plot_8-2021.csv")
GFBI_PlotSlice <- DominantRareSp_plotlevel %>% group_by(plot_id) %>% slice(1) #1:1826 #2:1174 #3:20 #4:10000 #5:9060 #6:1733

###Relationship between nr dominant species/nr rare species and plotsize
NrDomRare <- DominantRareSp_plotlevel %>% group_by(plot_id, DominanceCategory) %>% dplyr::mutate(Count=n_distinct(species_name))
NrDomRarePlot <- NrDomRare %>% group_by(plot_id, DominanceCategory) %>% slice(1)

NrDomPlot <- NrDomRarePlot[which(NrDomRarePlot$DominanceCategory=='dominant'),] 
NrRarePlot <- NrDomRarePlot[which(NrDomRarePlot$DominanceCategory=='rare'),] 

cor.test(NrDomPlot$Count, NrDomPlot$Plotsize, method = "spearman")
cor.test(NrRarePlot$Count, NrRarePlot$Plotsize, method = "spearman")

ggplot(NrDomPlot, aes(x=Plotsize, y=log(Sum))) + geom_point()
ggplot(NrRarePlot, aes(x=Plotsize, y=log(Sum))) + geom_point()

```
###Fig. 1
```{r Figure 1}
Biome_TraitsScaled <- fread("~/Documents/PhD projects/2nd Chapter - Trait diversity/Biome_TraitsScaledGlobally_8-2021.csv")
Biome_TraitsScaled <- subset(Biome_TraitsScaled, select=c(Biome, species_name, DominanceCategory, Height, CrownDiameter, BarkThickness, WoodDensity, SLA, LeafN, LeafNP, StemConduitDiameter, RootDepth, SeedMass))

Biome_TraitsDRScaled <- Biome_TraitsScaled[which(Biome_TraitsScaled$DominanceCategory == "rare" | Biome_TraitsScaled$DominanceCategory == "dominant"),]

Biome_TraitsDRCheck <- Biome_TraitsDRScaled %>% group_by(Biome, species_name) %>% count(DominanceCategory, sort = TRUE)

library(writexl)
write_xlsx(Biome_TraitsDRCheck, "Sp_Biomes.xlsx")
```
###Fig. 2 
```{r PCA traits}
###Match species with trait data
Traits <- read_feather("~/Documents/PhD projects/2nd Chapter - Trait diversity/GFBI_fixed_plots_ALL_TRAITS_7_21.feather") 

setnames(Traits, old = c("trait1055","trait1229","trait14","trait144", "trait145", "trait146", "trait15", "trait185", "trait21", "trait24", "trait26",  
                         "trait270", "trait281", "trait3106", "trait3110", "trait3117", "trait3120", "trait324", "trait4", "trait413", "trait44",                                     "trait45","trait46", "trait48", "trait54", "trait56", "trait6", "trait773", "trait80", "trait9"), 
         new = c("RootCN", "WoodN", "LeafN", "LeafLength", "LeafWidth", "LeafCN", "LeafP", "VcmaxDryMass", "StemDiameter", "BarkThickness", "SeedMass", 
                 "JmaxDryMass", "StemConduitDiameter", "Height", "LeafArea", "SLA", "LeafWaterMass", "CrownDiameter", "WoodDensity", "LeafChlorophyll",                      "LeafK", "StomatalConductance", "LeafThickness", "LeafDensity", "LeafRespRate", "LeafNP", "RootDepth", "CrownHeight", "RootN",                              "RootShootRatio"))

Traits_Select <- subset(Traits, select=c(obs_id, Height, CrownDiameter, BarkThickness, WoodDensity, SLA, LeafN, LeafNP, StemConduitDiameter, RootDepth, SeedMass))
rm(Traits)

DominantRare_Plot <- fread("~/Documents/PhD projects/2nd Chapter - Trait diversity/DominantRare_Plot_8-2021.csv")

DominantRare_Plot$genus <- word(DominantRare_Plot$species_name, 1) #Define gymnosperms/angiosperms
family <- getTaxonomy(DominantRare_Plot$genus) ###Add family name 
family$sperms <- ifelse(family$family == "Araucariaceae" |family$family == "Boweniaceae" |family$family == "Cephalotaxaceae" |family$family == "Cupressaceae" |family$family == "Cycadaceae" |family$family == "Ephedraceae" |family$family == "Ginkgoaceae" |family$family == "Gnetaceae" |family$family == "Pinaceae" |family$family == "Podocarpaceae" |family$family == "Taxaceae" |family$family == "Taxodiaceae" |family$family == "Welwitschiaceae" |family$family == "Zamiaceae", "gymnosperm", "angiosperm")

DominantRare_Plot$GymnoAngiosperm <- family$sperms

Plot_SpTraits <- left_join(DominantRare_Plot, Traits_Select, by="obs_id")
rm(DominantRare_Plot, Traits_Select)

###Log transform and scale traits 
Plot_SpTraitsCompl <- Plot_SpTraits[complete.cases(Plot_SpTraits),] #Only PercPerSpecies has NA values

Plot_SpTraitsLog <- Plot_SpTraits %>% mutate_at(vars(Height:SeedMass), log) #First log traits to normalise outliers
Plot_SpTraitsMean <- Plot_SpTraitsLog %>% group_by(plot_id, species_name) %>% slice(1) #Take mean trait per species/plot (there is no intra-specific variation within the plot anyhow)
Plot_TraitsNrInd <- Plot_SpTraitsLog %>% group_by(plot_id, species_name) %>% dplyr::summarise(NrIndSp=sum(NrInd)) 
Plot_TraitsMeanMerge <- as.data.frame(left_join(Plot_SpTraitsMean, Plot_TraitsNrInd, by=c("plot_id","species_name")))

Plot_TraitsScaled <- Plot_TraitsMeanMerge %>% mutate_at(vars(Height:SeedMass), scale) %>% as.data.frame() #Standardise trait values by Biome or globally group_by(Biome) %>% 

rm(Plot_SpTraits, Plot_SpTraitsCompl, Plot_SpTraitsLog, Plot_SpTraitsMean, Plot_TraitsNrInd, Plot_TraitsMeanMerge)

#########Add Temperature and Aridity
#Import and add GEE information
setwd("~/Documents/PhD projects/2nd Chapter - Trait diversity/Traits03-05-2021")
GEE <- as.data.frame(list.files("~/Documents/PhD projects/2nd Chapter - Trait diversity/Traits03-05-2021") %>% map_df(~fread(.))) #run at once with previous line
GEE_Select <- subset(GEE, select=c(plot_id, CHELSA_BIO_Annual_Mean_Temperature))

setwd("~/Documents/PhD projects/2nd Chapter - Trait diversity/TraitsPET_07-2021")
PET <- as.data.frame(list.files("~/Documents/PhD projects/2nd Chapter - Trait diversity/TraitsPET_07-2021") %>% map_df(~fread(.))) #run at once with previous line
PET_Select <- subset(PET, select=c(plot_id, CGIAR_Aridity_Index))

Env_vars <- merge(GEE_Select, PET_Select, by="plot_id")
setnames(Env_vars, old=c("CHELSA_BIO_Annual_Mean_Temperature", "CGIAR_Aridity_Index"), new=c("Temperature", "Humidity"))

Plot_TraitsEnv <- left_join(Plot_TraitsScaled, Env_vars, by="plot_id")
rm(GEE, PET, GEE_Select, PET_Select)

###Scaling of variables
Plot_TraitsEnv <- as.data.frame(Plot_TraitsEnv)
Plot_TraitsEnv$Temperature <- Plot_TraitsEnv$Temperature/10
Plot_TraitsEnv$Humidity <- Plot_TraitsEnv$Humidity*0.0001
Plot_TraitsEnv <- Plot_TraitsEnv[which(Plot_TraitsEnv$Humidity <= 4),] #69 plots removed
Plot_TraitsEnv <- Plot_TraitsEnv %>% dplyr::rename(Gymnosperm=GymnoAngiosperm)
Plot_TraitsEnv$Gymnosperm <- ifelse(Plot_TraitsEnv$Gymnosperm == "gymnosperm", 1, 0)
Plot_TraitsEnv <- Plot_TraitsEnv[complete.cases(Plot_TraitsEnv$Gymnosperm),]    

#########Create PCA
names(Plot_TraitsEnv)
Plot_TraitsDomRare <- Plot_TraitsEnv[which(Plot_TraitsEnv$DominanceCategory=="dominant" | Plot_TraitsEnv$DominanceCategory=="rare"),]
Plot_Traits_PCA <- Plot_TraitsDomRare %>% dplyr::select(Height, CrownDiameter, BarkThickness, WoodDensity, SLA, LeafN, LeafNP, StemConduitDiameter, RootDepth, SeedMass, Temperature, Humidity, Gymnosperm) 

setnames(Plot_Traits_PCA, old = c("Height", "CrownDiameter", "BarkThickness", "WoodDensity", "SLA", "LeafN", "LeafNP", "StemConduitDiameter", "RootDepth", "SeedMass"), 
         new = c("Height", "Crown diameter", "Bark thickness", "Wood density", "SLA", "Leaf N", "Leaf NP", "Stem conduit diameter", "Root depth", "Seed mass"))

pca_Traits <- prcomp(Plot_Traits_PCA, scale. = TRUE)

barplot(pca_Traits$rotation[,1], main="PC 1 Loadings Plot", las=2) #PCA statistics
barplot(pca_Traits$rotation[,2], main="PC 2 Loadings Plot", las=2)

pca.df_Traits <- data.frame(pca1 = pca_Traits$x[,1], pca2 = pca_Traits$x[,2], DominanceCategory = Plot_TraitsDomRare$DominanceCategory, Biome=Plot_TraitsDomRare$Biome)
pca.df_Traits2 <- data.frame(pca1 = pca_Traits$rotation[,1], pca2 = pca_Traits$rotation[,2],  labels = row.names(pca_Traits$rotation)) #, sig = pca_Traits$sig, #col=pca_Traits$col,
pca.df_Traits2$col <- c("#050505", "#050505", "#050505", "#050505", "#050505", "#050505", "#050505", "#050505", "#050505", "#050505", "#58038c", "#9e7306", "#1c6915")

#stat_ellipse(aes(group=factor(pca.df_Traits$DominanceCategory), color=factor(pca.df_Traits$DominanceCategory)), level = 0.68) + #, "deepskyblue", "blue1" #,"Dominant", "Rare"
Graph_pca_Traits <- ggplot(data=pca.df_Traits, aes(x=pca1, y=pca2)) + geom_point(aes(color = factor(pca.df_Traits$Biome), shape=factor(pca.df_Traits$DominanceCategory)), size = 4, alpha = 0.3) +  scale_color_manual(values = c("#ffdd03", "#8fd613", "#3f5220", "#0281a8", "#00549e", "#270169"), labels = c("Tropical moist", "Tropical dry", "Tropical conifer", "Temperate", "Temperate Conifer", "Boreal")) + 
  labs(x = "PCA 1 (41%)", y= "PCA 2 (25%)") + ggtitle("Traits dominant and rare tree species") + theme_bw() + labs(colour="Forest") + 
         theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(), 
          legend.position = "none", 
          plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
          legend.title=element_text(size=12, face="bold"),
          legend.text=element_text(size=12),
          axis.text.x = element_text(family="sans", size = 16, color = "black"),
          axis.text.y = element_text(family="sans", size = 16, color = "black"),
          axis.title.x = element_text(family="sans", size = 16, color = "black"),
          axis.title.y = element_text(family="sans", size = 16, color = "black")) +
          guides(colour = guide_legend(order = 1), shape = guide_legend(order = 2)) +
  geom_segment(data=pca.df_Traits2,aes(x=0, xend=pca1*8,y=0,yend=pca2*8), arrow = arrow(length = unit(0.5, "cm")), alpha = 1, colour=pca.df_Traits2$col, size=1.5) +    geom_text_repel(data=pca.df_Traits2,aes(x=8.5*pca1,y=9*pca2, label =labels), size=6, fontface="bold")

###Extract first and second axis PCA
Plot_TraitsDomRare$pca1 <- pca.df_Traits$pca1+4.707694 #min(pca.df_Traits$pca1)
Plot_TraitsDomRare$pca2 <- pca.df_Traits$pca2+4.580879 #min(pca.df_Traits$pca2)

###Relationships
Plot_Traits_PCA <- as.data.frame(Plot_Traits_PCA)

Plot_Traits_PCA$Temperature <- as.numeric(Plot_Traits_PCA$Temperature)
Plot_Traits_PCA$"Root depth" <- as.numeric(Plot_Traits_PCA$"Root depth")
cor.test(Plot_Traits_PCA$Temperature, Plot_Traits_PCA$"Root depth", method = "pearson")

cor.test(Plot_Traits_PCA$Humidity, Plot_Traits_PCA$Height, method = "spearman")
cor.test(Plot_Traits_PCA$Humidity, Plot_Traits_PCA$"Bark thickness", method = "pearson")
cor.test(Plot_Traits_PCA$Temperature, Plot_Traits_PCA$"Bark thickness", method = "pearson")


```
###Fig. 3 
```{r Boxplots}

####Calculate percentage gymnosperm individuals per plot
DominantRare_Plot_select <- DominantRare_Plot[complete.cases(DominantRare_Plot$species_name),] #Select only identified trees
DominantRare_Plot_CountGymno <- as.data.frame(DominantRare_Plot_select %>% group_by(plot_id, DominanceCategory) %>% dplyr::count(GymnoAngiosperm)) #Sum of individuals per plot
DominantRare_CountGymno <- DominantRare_Plot_CountGymno[which(DominantRare_Plot_CountGymno$GymnoAngiosperm=="gymnosperm"),]
DominantRare_CountGymno <- DominantRare_CountGymno %>% dplyr::rename("Gymnosperm" = n) %>% dplyr::select(-GymnoAngiosperm)  %>% as.data.frame() 

Plots_DominantRare_PercInd <- DominantRare_Plot %>% group_by(plot_id, DominanceCategory) %>% dplyr::mutate(., NrIndCategory = sum(n())) %>% slice(1)
Plots_DominantRare_Plot <- Plots_DominantRare_PercInd %>% dplyr::select(plot_id, DominanceCategory, NrIndCategory)

DominantRare_Gymno <- left_join(Plots_DominantRare_Plot, DominantRare_CountGymno)
DominantRare_Gymno$Gymnosperm[is.na(DominantRare_Gymno$Gymnosperm)] <- 0
DominantRare_Gymno_perc <- as.data.frame(DominantRare_Gymno %>% group_by(plot_id, DominanceCategory) %>% mutate(PercInd_gymnosperm=(Gymnosperm/NrIndCategory)*100))
DominantRare_Gymno_perc <- DominantRare_Gymno_perc %>% dplyr::select(plot_id, DominanceCategory, PercInd_gymnosperm)

DominantRare_Gymno_DomRare <- DominantRare_Gymno_perc[which(DominantRare_Gymno_perc$DominanceCategory=="dominant" | DominantRare_Gymno_perc$DominanceCategory=="rare"), ]

###Difference between CWM dominant and rare species traits
Plot_TraitsDRScaled <- Plot_TraitsDomRare %>% group_by(Biome, plot_id, DominanceCategory) %>% dplyr::summarise_at(vars(Height:pca2), median, na.rm = TRUE) %>% as.data.frame()

Plot_TraitsDRScaled <- left_join(Plot_TraitsDRScaled, DominantRare_Gymno_DomRare)

Plot_TraitsD <- Plot_TraitsDRScaled[which(Plot_TraitsDRScaled$DominanceCategory == "dominant"),]
Plot_TraitsR <- Plot_TraitsDRScaled[which(Plot_TraitsDRScaled$DominanceCategory == "rare"),]

#Calculate difference dominant-rare species median trait values
JoinRare <- anti_join(Plot_TraitsR, Plot_TraitsD, by="plot_id")
JoinDom <- anti_join(Plot_TraitsD, Plot_TraitsR, by="plot_id")

CWMDomFilter <- anti_join(Plot_TraitsD, JoinDom, by="plot_id")
CWMDomOrder <- CWMDomFilter[order(CWMDomFilter$plot_id),]
CWMDomSubset <- as.data.frame(subset(CWMDomOrder, select=-c(plot_id, DominanceCategory, Biome)))

CWMRareFilter <- anti_join(Plot_TraitsR, JoinRare, by="plot_id")
CWMRareOrder <- CWMRareFilter[order(CWMRareFilter$plot_id),]
CWMRareSubset <- as.data.frame(subset(CWMRareOrder, select=-c(plot_id, DominanceCategory, Biome)))

DiffDomRare_CWM <- CWMDomSubset - CWMRareSubset
DiffDomRare_CWM$plot_id <- CWMRareOrder$plot_id
DiffDomRare_CWM$Biome <- as.numeric(CWMRareOrder$Biome)

TraitsDiffMean <- as.data.frame(DiffDomRare_CWM %>% group_by(Biome) %>% dplyr::summarise(n = n(), MeanHeight=mean(Height), seHeight=(sd(Height)/sqrt(n)),lowCIHeight = ci(Height)[2], hiCIHeight = ci(Height)[3], MeanCrownDiameter=mean(CrownDiameter), seCrownDiameter=(sd(CrownDiameter)/sqrt(n)), lowCICrownDiameter = ci(CrownDiameter)[2], hiCICrownDiameter = ci(CrownDiameter)[3], MeanBarkThickness=mean(BarkThickness), seBarkThickness=(sd(BarkThickness)/sqrt(n)), lowCIBarkThickness = ci(BarkThickness)[2], hiCIBarkThickness = ci(BarkThickness)[3], MeanWoodDensity=mean(WoodDensity), seWoodDensity=(sd(WoodDensity)/sqrt(n)), lowCIWoodDensity = ci(WoodDensity)[2], hiCIWoodDensity = ci(WoodDensity)[3], MeanSLA=mean(SLA), seSLA=(sd(SLA)/sqrt(n)), lowCISLA = ci(SLA)[2], hiCISLA = ci(SLA)[3], MeanLeafN=mean(LeafN), seLeafN=(sd(LeafN)/sqrt(n)), lowCILeafN = ci(LeafN)[2], hiCILeafN = ci(LeafN)[3], MeanLeafNP=mean(LeafNP), seLeafNP=(sd(LeafNP)/sqrt(n)), lowCILeafNP = ci(LeafNP)[2], hiCILeafNP = ci(LeafNP)[3], MeanStemConduitD=mean(StemConduitDiameter), seStemConduitD=(sd(StemConduitDiameter)/sqrt(n)), lowCIStemConduitD = ci(StemConduitDiameter)[2], hiCIStemConduitD = ci(StemConduitDiameter)[3], MeanRootDepth=mean(RootDepth), seRootDepth=(sd(RootDepth)/sqrt(n)), lowCIRootDepth = ci(RootDepth)[2], hiCIRootDepth = ci(RootDepth)[3], MeanSeedMass=mean(SeedMass), seSeedMass=(sd(SeedMass)/sqrt(n)), lowCISeedMass = ci(SeedMass)[2], hiCISeedMass = ci(SeedMass)[3], MeanPercInd_gymnosperm=mean(PercInd_gymnosperm), sePercInd_gymnosperm=(sd(PercInd_gymnosperm)/sqrt(n)), lowCIPercInd_gymnosperm = ci(PercInd_gymnosperm)[2], hiCIPercInd_gymnosperm = ci(PercInd_gymnosperm)[3], Meanpca1=mean(pca1), sepca1=(sd(pca1)/sqrt(n)), lowCIpca1 = ci(pca1)[2], hiCIpca1 = ci(pca1)[3], Meanpca2=mean(pca2), sepca2=(sd(pca2)/sqrt(n)), lowCIpca2 = ci(pca2)[2], hiCIpca2 = ci(pca2)[3]))

###Calculate mean differences pr biome
TraitsDiffMean_select <- TraitsDiffMean %>% dplyr::select(Biome, starts_with("Mean")) %>% dplyr::select(-MeanPercInd_gymnosperm, -Meanpca1, -Meanpca2)
TraitsDifferencesBiome <- TraitsDiffMean_select %>% rowwise() %>% mutate(mean = mean(abs(c_across(starts_with("Mean")))), na.rm = TRUE) %>% ungroup()

###Statistics
Plot_TraitsDRScaled$DominanceCategory <- ifelse(Plot_TraitsDRScaled$DominanceCategory == "dominant", "2", "1") #2=dominant, 1=rare
Plot_TraitsDRScaled$DominanceCategory <- as.numeric(Plot_TraitsDRScaled$DominanceCategory)

Results_Wilcoxon <- as.data.frame(Plot_TraitsDRScaled %>% group_by(Biome) %>% dplyr::summarise(Pvalue_Height = wilcox.test(Height ~ DominanceCategory)$p.value,
                                                             Pvalue_CrownDiameter = wilcox.test(CrownDiameter ~ DominanceCategory)$p.value,
                                                             Pvalue_BarkThickness = wilcox.test(BarkThickness ~ DominanceCategory)$p.value,
                                                             Pvalue_WoodDensity = wilcox.test(WoodDensity ~ DominanceCategory)$p.value,
                                                             Pvalue_SLA = wilcox.test(SLA ~ DominanceCategory)$p.value,
                                                             Pvalue_LeafN = wilcox.test(LeafN ~ DominanceCategory)$p.value,
                                                             Pvalue_LeafNP = wilcox.test(LeafNP ~ DominanceCategory)$p.value,
                                                             Pvalue_StemConduitDiameter = wilcox.test(StemConduitDiameter ~ DominanceCategory)$p.value,
                                                             Pvalue_RootDepth = wilcox.test(RootDepth ~ DominanceCategory)$p.value,
                                                             Pvalue_SeedMass = wilcox.test(SeedMass ~ DominanceCategory)$p.value,
                                                             Pvalue_Gymnosperm = wilcox.test(PercInd_gymnosperm ~ DominanceCategory)$p.value,
                                                             Pvalue_pca1 = wilcox.test(pca1 ~ DominanceCategory)$p.value,
                                                             Pvalue_pca2 = wilcox.test(pca2 ~ DominanceCategory)$p.value))

Results_Wilcoxon_nr <- Results_Wilcoxon %>% dplyr::mutate(across(c(2:14), ~ifelse(. <= 0.05, 1, 0)))

#Join datasets
TraitsDiffMean <- left_join(TraitsDiffMean, Results_Wilcoxon_nr)

##Boxplots standard error 
TraitsDiffMean <- TraitsDiffMean[which(TraitsDiffMean$Biome!=3),]

#####Add significance level
BoxplotLeafN <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanLeafN, colour=factor(Biome), shape=factor(Pvalue_LeafN))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169"),
                     labels = c("Tropical moist", "Tropical dry", "Temperate", "Temperate conifer",  "Boreal")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCILeafN, ymax=hiCILeafN), color="black", width=.1) + #ymin=MeanLeafN-seLeafN, ymax=MeanLeafN+seLeafN
  labs(title="Leaf nitrogen") +
  labs(x=" ", y="Δ Leaf N") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank()) + 
  scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none") #bottom

BoxplotLeafNP <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanLeafNP, colour=factor(Biome), shape=factor(Pvalue_LeafNP))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCILeafNP, ymax=hiCILeafNP), color="black", width=.1) + #ymin=MeanLeafNP-seLeafNP, ymax=MeanLeafNP+seLeafNP
  labs(title="Leaf N/P ratio") +
  labs(x=" ", y="Δ Leaf NP") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank()) + scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotStemConduitD <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanStemConduitD, colour=factor(Biome), shape=factor(Pvalue_StemConduitDiameter))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIStemConduitD, ymax=hiCIStemConduitD), color="black", width=.1) + #ymin=MeanStemConduitD-seStemConduitD, ymax=MeanStemConduitD+seStemConduitD
  labs(title="Stem Conduit Diameter") +
  labs(x=" ", y="Δ Stem Conduit Diam.") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank()) + scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotSeedMass <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanSeedMass, colour=factor(Biome), shape=factor(Pvalue_SeedMass))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCISeedMass, ymax=hiCISeedMass), color="black", width=.1) + #ymin=MeanSeedMass-seSeedMass, ymax=MeanSeedMass+seSeedMass
  labs(title="Seed mass") +
  labs(x=" ", y="Δ Seed mass") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank()) + scale_x_discrete(position="bottom", breaks = c("1", "2", "3", "4", "5", "6"), labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+ # labels=c("Tropical Moist", "Tropical dry", "Tropical conifer", "Temperate", "Temperate conifer",  "Boreal"))
  theme(plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 14),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

# grid.arrange(BoxplotStemConduitD, BoxplotLeafN, BoxplotLeafNP, BoxplotSeedMass, nrow=2, top=textGrob("Traits dominant and rare species", gp=gpar(col="black", fontsize=25, fontface="bold")), padding = unit(3,"line"))

BoxplotHeight <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanHeight, colour=factor(Biome), shape=factor(Pvalue_Height))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(19, 21)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIHeight, ymax=hiCIHeight), color="black", width=.1) + #ymin=MeanHeight-seHeight, ymax=MeanHeight+seHeight
  labs(title="Tree Height") + labs(x=" ", y="Δ Tree height") + geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotCrownDiameter <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanCrownDiameter, colour=factor(Biome), shape=factor(Pvalue_CrownDiameter))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCICrownDiameter, ymax=hiCICrownDiameter), color="black", width=.1) + #ymin=MeanCrownDiameter-seCrownDiameter, ymax=MeanCrownDiameter+seCrownDiameter
  labs(title="Crown diameter") +
  labs(x=" ", y="Δ Crown diameter") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotWoodDensity <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanWoodDensity, colour=factor(Biome), shape=factor(Pvalue_WoodDensity))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(19, 21)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIWoodDensity, ymax=hiCIWoodDensity), color="black", width=.1) + #ymin=MeanWoodDensity-seWoodDensity, ymax=MeanWoodDensity+seWoodDensity
  labs(title="Wood density") +
  labs(x=" ", y="Δ Wood density") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotBarkThickness <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanBarkThickness, colour=factor(Biome), shape=factor(Pvalue_BarkThickness))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIBarkThickness, ymax=hiCIBarkThickness), color="black", width=.1) + #ymin=MeanBarkThickness-seBarkThickness, ymax=MeanBarkThickness+seBarkThickness
  labs(title="Bark thickness") +
  labs(x=" ", y="Δ Bark thickness") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotSLA <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanSLA, colour=factor(Biome), shape=factor(Pvalue_SLA))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21, 19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCISLA, ymax=hiCISLA), color="black", width=.1) + #ymin=MeanSLA-seSLA, ymax=MeanSLA+seSLA
  labs(title="Specific leaf area") +
  labs(x=" ", y="Δ SLA") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom",labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotRootDepth <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanRootDepth, colour=factor(Biome), shape=factor(Pvalue_RootDepth))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIRootDepth, ymax=hiCIRootDepth), color="black", width=.1) + #ymin=MeanRootDepth-seRootDepth, ymax=MeanRootDepth+seRootDepth
  labs(title="Root depth") +
  labs(x=" ", y="Δ Root depth") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom", labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 14),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

BoxplotGymnosperm <- ggplot(TraitsDiffMean, aes(x=Biome, y=MeanPercInd_gymnosperm, colour=factor(Biome), shape=factor(Pvalue_Gymnosperm))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIPercInd_gymnosperm, ymax=hiCIPercInd_gymnosperm), color="black", width=.1) + #ymin=MeanPercInd_gymnosperm-sePercInd_gymnosperm, ymax=MeanPercInd_gymnosperm+sePercInd_gymnosperm
  labs(title="Gymnosperm") +
  labs(x=" ", y="Δ gymnosperm %") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom", labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 14),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

Boxplotpca1 <- ggplot(TraitsDiffMean, aes(x=Biome, y=Meanpca1, colour=factor(Biome), shape=factor(Pvalue_pca1))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(19, 21)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIpca1, ymax=hiCIpca1), color="black", width=.1) + #ymin=Meanpca1-sepca1, ymax=Meanpca1+sepca1
  labs(title="pca 1") +
  labs(x=" ", y="Δ pca 1") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom", labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 14),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

Boxplotpca2 <- ggplot(TraitsDiffMean, aes(x=Biome, y=Meanpca2, colour=factor(Biome), shape=factor(Pvalue_pca2))) + geom_point(size=4, position = position_dodge(width=0.75)) +
  scale_color_manual(values = c("#ffdd03", "#8fd613", "#0281a8", "#00549e", "#270169")) +
  scale_shape_manual(values = c(21,19)) + #0=non sig, 1=sig
  geom_errorbar(aes(ymin=lowCIpca2, ymax=hiCIpca2), color="black", width=.1) + #ymin=Meanpca2-sepca2, ymax=Meanpca2+sepca2
  labs(title="pca 2") +
  labs(x=" ", y="Δ pca 2") +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey", size=0.5) +
  theme_linedraw()+ scale_x_discrete(position="bottom", labels=c("Trop Moist", "Trop Dry", "Trop Conifer", "Temperate", "Temp Conifer",  "Boreal"))+
  theme(panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(),
        plot.title = element_text(hjust = 0.5, size = 19, face = "bold"),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(angle = 25, vjust = 0.5, size = 14),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        legend.position = "none")

Fig3 <- grid.arrange(BoxplotHeight, BoxplotWoodDensity, BoxplotLeafN, BoxplotSeedMass, BoxplotRootDepth, Boxplotpca1, nrow=4, top=textGrob("Traits of dominant and rare species", gp=gpar(col="black", fontsize=20, fontface="bold")), padding = unit(3,"line"))

GraphsSI <- grid.arrange(BoxplotCrownDiameter, BoxplotBarkThickness, BoxplotStemConduitD, BoxplotSLA, BoxplotLeafNP,  BoxplotGymnosperm, Boxplotpca2,  nrow=4, top=textGrob("Traits of dominant and rare species", gp=gpar(col="black", fontsize=20, fontface="bold")), padding = unit(3,"line"))

```
###Fig. 4
```{r Temperature & Aridity}
#Pair up with environmental variables
#Import and add GEE information
setwd("~/Documents/PhD projects/2nd Chapter - Trait diversity/Traits03-05-2021")
GEE <- as.data.frame(list.files("~/Documents/PhD projects/2nd Chapter - Trait diversity/Traits03-05-2021") %>% map_df(~fread(.))) #run at once with previous line
GEE_Select <- subset(GEE, select=c(plot_id, CHELSA_BIO_Annual_Mean_Temperature, CHELSA_BIO_Annual_Precipitation, CHELSA_BIO_Precipitation_Seasonality, CHELSA_BIO_Temperature_Seasonality, EarthEnvTopoMed_Elevation, GFAD_FractionOfRegrowthForest_downsampled50km, GFAD_regrowthForestAge_Mean_downsampled50km))

setwd("~/Documents/PhD projects/2nd Chapter - Trait diversity/TraitsPET_07-2021")
PET <- as.data.frame(list.files("~/Documents/PhD projects/2nd Chapter - Trait diversity/TraitsPET_07-2021") %>% map_df(~fread(.))) #run at once with previous line
PET_Select <- subset(PET, select=c(plot_id, CGIAR_Aridity_Index, CGIAR_PET))

Env_vars <- merge(GEE_Select, PET_Select, by="plot_id")
setnames(Env_vars, old=c("CHELSA_BIO_Annual_Mean_Temperature", "CHELSA_BIO_Annual_Precipitation", "CHELSA_BIO_Precipitation_Seasonality",  "CHELSA_BIO_Temperature_Seasonality", "EarthEnvTopoMed_Elevation", "GFAD_FractionOfRegrowthForest_downsampled50km", "GFAD_regrowthForestAge_Mean_downsampled50km", "CGIAR_Aridity_Index", "CGIAR_PET"), new=c("Temperature", "Precipitation", "Precipitation_Seasonality", "Temperature_Seasonality", "Elevation", "Secondary_Forest", "Forest_Age", "Aridity", "PET"))

DifCWM_Envars <- left_join(DiffDomRare_CWM, Env_vars, by="plot_id")
rm(GEE, PET, GEE_Select, PET_Select)

#Relationship temperature-aridity
DifCWM_Envars$Temperature <- DifCWM_Envars$Temperature.y
cor.test(DifCWM_Envars$Aridity, DifCWM_Envars$Temperature, method = "pearson") #-0.09, p<0.001
cor.test(DifCWM_Envars$Aridity, DifCWM_Envars$Temperature, method = "spearman") #-0.16, p<0.001

###Aridity graphs
DifCWM_Envars <- as.data.frame(DifCWM_Envars)

DifCWM_Envars$Temperature <- DifCWM_Envars$Temperature/10
DifCWM_Envars$Aridity <- DifCWM_Envars$Aridity*0.0001
DifCWM_Envars <- DifCWM_Envars[which(DifCWM_Envars$Aridity <= 4),] #69 plots removed

#############MAIN TEXT
Height_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, Height)) + #linear relationship (quadratic relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.03***", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) + xlab(" ") + ylab("Δ Height") + #labs(title="Height") +
  geom_ribbon(aes(ymin = 0,ymax = predict(lm(Height  ~ Aridity), data=DifCWM_Envars)), alpha = 0.8,fill = "#9e7306")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

RootDepth_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, RootDepth)) + #Quadratic relationship (linear relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(c(0, 4)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.01***", x = 3.5, y = 0.8, size = 6, colour = "black") + 
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(RootDepth ~ Aridity), data=DifCWM_Envars)), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.6, y = 0, xend = 1.6, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Root Depth")+ #labs(title="Root Depth") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

StemConduitDiameter_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, StemConduitDiameter)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.03***", x = 3.5, y = -0.8, size = 6, colour = "black") +
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(StemConduitDiameter ~ Aridity), data=DifCWM_Envars)), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.65, y = 0, xend = 1.65, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Stem Conduit Diam.")+ #labs(title="Stem Conduit Diam.") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

SLA_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, SLA)) + #Quadratic relationship (linear relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.05***", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(SLA ~ Aridity), data=DifCWM_Envars)), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.55, y = 0, xend = 1.55, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ SLA")+ #labs(title="SLA") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

pca1_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, pca1)) + #Quadratic relationship with log(y) (linear relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(0,4) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.1***", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(pca1 ~ Aridity), data=DifCWM_Envars)), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.7, y = 0, xend = 1.7, yend = -Inf), size=0.5, linetype="dashed") +
  xlab("Humidity Index") + ylab("Δ pca1")+ #labs(title="pca1") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

#############SI
CrownDiameter_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, CrownDiameter)) + #linear with log(y) (quadratic relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "<0.01", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) + xlab(" ") + ylab("Δ Crown Diam.")+ #labs(title="Crown Diameter") +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(CrownDiameter ~ Aridity, data=DifCWM_Envars))), alpha = 0.8,fill = "#9e7306")+
  geom_segment(aes(x = 1.6, y = 0, xend = 1.6, yend = -Inf), size=0.5, linetype="dashed") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

WoodDensity_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, WoodDensity)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.08***", x = 3.5, y = -0.8, size = 6, colour = "black") + theme_classic()+ 
  geom_hline(yintercept=0, color = "grey", size=1) + xlab(" ") + ylab("Δ Wood Density")+ #labs(title="Wood density") +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(WoodDensity ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.7, y = 0, xend = 1.7, yend = -Inf), size=0.5, linetype="dashed") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)
  
BarkThickness_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, BarkThickness)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.02***", x = 3.5, y =0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(BarkThickness ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 2.8, y = 0, xend = 2.8, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Bark thickness")+ #labs(title="Bark thickness") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

LeafN_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, LeafN)) + #Quadratic relationship (linear relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(0,4) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.03***", x = 3.5, y = -0.8, size = 6, colour = "black") +
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(LeafN ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.65, y = 0, xend = 1.65, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Leaf N")+ #labs(title="Leaf N") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

LeafNP_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, LeafNP)) + #Quadratic relationship (linear relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(0,4) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.03***", x = 3.5, y = 0.8, size = 6, colour = "black") +theme_classic()+ 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(LeafNP ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.65, y = 0, xend = 1.65, yend = -Inf), size=0.5, linetype="dashed") +
  xlab("Humidity Index") + ylab("Δ Leaf NP")+ #labs(title="Leaf NP") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

SeedMass_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, SeedMass)) + #Linear relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(0,4) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.02***", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(SeedMass ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.7, y = 0, xend = 1.7, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Seed Mass")+ #labs(title="Seed Mass") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

Gymnosperm_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, PercInd_gymnosperm)) + #Linear relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(0,4) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.05***", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(PercInd_gymnosperm ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  #geom_segment(aes(x = 1.7, y = 0, xend = 1.7, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Gymnosperm %")+ #labs(title="Seed Mass") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size="none")

pca2_Aridity <- ggplot(DifCWM_Envars, aes(Aridity, pca2)) + #linear relationship or quadratic relationship with log(y)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm") + xlim(0,4) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.02***", x = 3.5, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(pca2 ~ Aridity, data=DifCWM_Envars))), alpha = 0.8, fill = "#9e7306")+
  geom_segment(aes(x = 1.7, y = 0, xend = 1.7, yend = -Inf), size=0.5, linetype="dashed") +
  xlab("Humidity Index") + ylab("Δ pca2")+ #labs(title="pca2") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

###Temperature graphs
#############MAIN TEXT
Height_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, Height)) + #Quadratic relationship with log(y) (linear relationship as good)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.06***", x = 23, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) + #linetype="dashed", 
  xlab(" ") + ylab("Δ Height")+ 
  geom_ribbon(aes(ymin = 0,ymax = predict(lm(Height  ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8,fill = "#58038c")+
  geom_segment(aes(x = 26, y = 0, xend = 26, yend = -Inf), size=0.5, linetype="dashed") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

RootDepth_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, RootDepth)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.03***", x = 23, y = 0.8, size = 6, colour = "black") + 
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(RootDepth ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Root Depth")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

StemConduitDiameter_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, StemConduitDiameter)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.06***", x = 23, y = 0.8, size = 6, colour = "black") +
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(StemConduitDiameter ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Stem Conduit Diam.")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)
  
SLA_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, SLA)) + #Quadratic relationship with log(y)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.09***", x = 23, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(SLA ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 6, y = 0, xend = 6, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ SLA")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

pca1_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, pca1)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.14***", x = 23, y = -0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(pca1 ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab("Temperature °C") + ylab("Δ pca1")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

#############SI
CrownDiameter_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, CrownDiameter)) + #Quadratic term with log(y) (as good as with y)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.06***", x = 23, y = 0.8, size = 6, colour = "black") +
  theme_classic() + geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(CrownDiameter ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Crown Diam.")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

WoodDensity_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, WoodDensity)) + #Quadratic term with log(y) (as good as with y)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.05***", x = 23, y = 0.8, size = 6, colour = "black") +
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(WoodDensity ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 6.5, y = 0, xend = 6.5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Wood Density")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)
  
BarkThickness_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, BarkThickness)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.03***", x = 23, y =0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(BarkThickness ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 23, y = 0, xend = 23, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Bark thickness")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

LeafN_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, LeafN)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.07***", x = 23, y = 0.8, size = 6, colour = "black") +
  theme_classic()+ geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(LeafN ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Leaf N")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

LeafNP_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, LeafNP)) + #Quadratic relationship
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "0.03***", x = 25, y = 0.8, size = 6, colour = "black") +theme_classic()+ 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(LeafNP ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 4, y = 0, xend = 4, yend = -Inf), size=0.5, linetype="dashed") +
  xlab("Temperature °C") + ylab("Δ Leaf NP")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

SeedMass_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, SeedMass)) + #Quadratic relationship with log(y) (as good as linear relationship)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.01***", x = 23, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(SeedMass ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Seed Mass")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

Gymnosperm_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, PercInd_gymnosperm)) + #Quadratic relationship with log(y) (as good as linear relationship)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.04***", x = 23, y = -0.5, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(PercInd_gymnosperm ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  #geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed") +
  xlab(" ") + ylab("Δ Gymnosperm %")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

pca2_Temperature <- ggplot(DifCWM_Envars, aes(Temperature, pca2)) + #Quadratic relationship with log(y)
  geom_smooth(size= 2, colour="#0a0a0a", method="lm", formula=y ~ poly(x, 2, raw=TRUE)) + coord_cartesian(ylim=c(-1, 1)) +
  annotate("text", label = "-0.09***", x = 23, y = 0.8, size = 6, colour = "black") + theme_classic() + 
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_ribbon(aes(ymin = 0, ymax = predict(lm(pca2 ~ poly(Temperature, 2, raw=TRUE), data=DifCWM_Envars))), alpha = 0.8, fill = "#58038c")+
  geom_segment(aes(x = 8, y = 0, xend = 8, yend = -Inf), size=0.5, linetype="dashed") +
  xlab("Temperature °C") + ylab("Δ pca2")+
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_blank()) +
  guides(size=FALSE)

##############Final graphs
###MAIN text
Graphs_Aridity <- grid.arrange(Height_Aridity, WoodDensity_Aridity, LeafN_Aridity, SeedMass_Aridity, RootDepth_Aridity,  pca1_Aridity, nrow=6)
Graphs_Temp <- grid.arrange(Height_Temperature, WoodDensity_Temperature, LeafN_Temperature, SeedMass_Temperature, RootDepth_Temperature,  pca1_Temperature, nrow=6)
Graph4 <- grid.arrange(Graphs_Temp, Graphs_Aridity, ncol=2, top=textGrob("Trait differences correlated with climate", gp=gpar(col="black", fontsize=21, fontface="bold")), padding = unit(3,"line"))

###SI
SI_Aridity_A <- grid.arrange(CrownDiameter_Aridity, BarkThickness_Aridity, StemConduitDiameter_Aridity, SLA_Aridity, LeafNP_Aridity, nrow=5)
SI_Temp_A <- grid.arrange(CrownDiameter_Temperature,  BarkThickness_Temperature, StemConduitDiameter_Temperature, SLA_Temperature, LeafNP_Temperature, nrow=5)
FigS2A <- grid.arrange(SI_Temp_A, SI_Aridity_A, ncol=2, top=textGrob("Trait differences correlated with climate", gp=gpar(col="black", fontsize=21, fontface="bold")), padding = unit(3,"line"))

SI_Aridity_B <- grid.arrange(CrownDiameter_Aridity,  BarkThickness_Aridity, StemConduitDiameter_Aridity, Gymnosperm_Aridity, pca2_Aridity, nrow=5)
SI_Temp_B <- grid.arrange(CrownDiameter_Temperature,  BarkThickness_Temperature, StemConduitDiameter_Temperature, Gymnosperm_Temperature, pca2_Temperature, nrow=5)
FigS2B <- grid.arrange(SI_Temp_B, SI_Aridity_B, ncol=2, padding = unit(3,"line")) #top=textGrob("Trait differences correlated with climate", gp=gpar(col="black", fontsize=25, fontface="bold"))

######Model
Plotsize <- DominantRare_Plot %>% dplyr::select(Biome, plot_id, Plotsize)
DifCWM_Envars <- left_join(DifCWM_Envars, Plotsize, by=c("Biome", "plot_id")) #Add Plotsize

model_Height <- lm(Height ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_Height)
VarImp_Height <- calc.relimp(model_Height, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*: contributing >5%
VarImp_Height <- as.data.frame(VarImp_Height@lmg)
VarImp_Height_Final <- VarImp_Height %>% rename(VarImp=`VarImp_Height@lmg`)
VarImp_Height_Final <- cbind(VarImp_Height_Final, summary(model_Height)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_Height_Final$Variable <- "Height"

model_CrownDiameter <- lm(CrownDiameter ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_CrownDiameter)
VarImp_CrownDiameter <- calc.relimp(model_CrownDiameter, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity*: contributing >5%
VarImp_CrownDiameter <- as.data.frame(VarImp_CrownDiameter@lmg)
VarImp_CrownDiameter_Final <- VarImp_CrownDiameter %>% rename(VarImp=`VarImp_CrownDiameter@lmg`)
VarImp_CrownDiameter_Final <- cbind(VarImp_CrownDiameter_Final, summary(model_CrownDiameter)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_CrownDiameter_Final$Variable <- "CrownDiameter"

model_BarkThickness <- lm(BarkThickness ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_BarkThickness)
VarImp_BarkThickness <- calc.relimp(model_BarkThickness, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*: contributing >5%
VarImp_BarkThickness <- as.data.frame(VarImp_BarkThickness@lmg)
VarImp_BarkThickness_Final <- VarImp_BarkThickness %>% rename(VarImp=`VarImp_BarkThickness@lmg`)
VarImp_BarkThickness_Final <- cbind(VarImp_BarkThickness_Final, summary(model_BarkThickness)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_BarkThickness_Final$Variable <- "BarkThickness"

model_WoodDensity <- lm(WoodDensity ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_WoodDensity)
VarImp_WoodDensity <- calc.relimp(model_WoodDensity, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity*: contributing >5%
VarImp_WoodDensity <- as.data.frame(VarImp_WoodDensity@lmg)
VarImp_WoodDensity_Final <- VarImp_WoodDensity %>% rename(VarImp=`VarImp_WoodDensity@lmg`)
VarImp_WoodDensity_Final <- cbind(VarImp_WoodDensity_Final, summary(model_WoodDensity)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_WoodDensity_Final$Variable <- "WoodDensity"

model_SLA <- lm(SLA ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_SLA)
VarImp_SLA <- calc.relimp(model_SLA, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity: contributing >5%
VarImp_SLA <- as.data.frame(VarImp_SLA@lmg)
VarImp_SLA_Final <- VarImp_SLA %>% rename(VarImp=`VarImp_SLA@lmg`)
VarImp_SLA_Final <- cbind(VarImp_SLA_Final, summary(model_SLA)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_SLA_Final$Variable <- "SLA"

model_LeafN <- lm(LeafN ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_LeafN)
VarImp_LeafN <- calc.relimp(model_LeafN, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_LeafN <- as.data.frame(VarImp_LeafN@lmg)
VarImp_LeafN_Final <- VarImp_LeafN %>% rename(VarImp=`VarImp_LeafN@lmg`)
VarImp_LeafN_Final <- cbind(VarImp_LeafN_Final, summary(model_LeafN)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_LeafN_Final$Variable <- "LeafN"

model_LeafNP <- lm(LeafNP ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_LeafNP)
VarImp_LeafNP <- calc.relimp(model_LeafNP, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_LeafNP <- as.data.frame(VarImp_LeafNP@lmg)
VarImp_LeafNP_Final <- VarImp_LeafNP %>% rename(VarImp=`VarImp_LeafNP@lmg`)
VarImp_LeafNP_Final <- cbind(VarImp_LeafNP_Final, summary(model_LeafNP)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_LeafNP_Final$Variable <- "LeafNP"

model_StemConduitDiam <- lm(StemConduitDiameter ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_StemConduitDiam)
VarImp_StemConduitDiam <- calc.relimp(model_StemConduitDiam, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_StemConduitDiam <- as.data.frame(VarImp_StemConduitDiam@lmg)
VarImp_StemConduitDiam_Final <- VarImp_StemConduitDiam %>% rename(VarImp=`VarImp_StemConduitDiam@lmg`)
VarImp_StemConduitDiam_Final <- cbind(VarImp_StemConduitDiam_Final, summary(model_StemConduitDiam)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_StemConduitDiam_Final$Variable <- "StemConduitDiam"

model_RootDepth <- lm(RootDepth ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_RootDepth)
VarImp_RootDepth <- calc.relimp(model_RootDepth, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_RootDepth <- as.data.frame(VarImp_RootDepth@lmg)
VarImp_RootDepth_Final <- VarImp_RootDepth %>% rename(VarImp=`VarImp_RootDepth@lmg`)
VarImp_RootDepth_Final <- cbind(VarImp_RootDepth_Final, summary(model_RootDepth)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_RootDepth_Final$Variable <- "RootDepth"

model_SeedMass <- lm(SeedMass ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_SeedMass)
VarImp_SeedMass <- calc.relimp(model_SeedMass, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_SeedMass <- as.data.frame(VarImp_SeedMass@lmg)
VarImp_SeedMass_Final <- VarImp_SeedMass %>% rename(VarImp=`VarImp_SeedMass@lmg`)
VarImp_SeedMass_Final <- cbind(VarImp_SeedMass_Final, summary(model_SeedMass)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_SeedMass_Final$Variable <- "SeedMass"

model_Gymnosperm <- lm(scale(PercInd_gymnosperm) ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_Gymnosperm)
VarImp_Gymnosperm <- calc.relimp(model_Gymnosperm, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_Gymnosperm <- as.data.frame(VarImp_Gymnosperm@lmg)
VarImp_Gymnosperm_Final <- VarImp_Gymnosperm %>% dplyr::rename(VarImp="VarImp_Gymnosperm@lmg")
VarImp_Gymnosperm_Final <- cbind(VarImp_Gymnosperm_Final, summary(model_Gymnosperm)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_Gymnosperm_Final$Variable <- "Gymnosperm"

model_pca1 <- lm(pca1 ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_pca1)
VarImp_pca1 <- calc.relimp(model_pca1, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_pca1 <- as.data.frame(VarImp_pca1@lmg)
VarImp_pca1_Final <- VarImp_pca1 %>% rename(VarImp=`VarImp_pca1@lmg`)
VarImp_pca1_Final <- cbind(VarImp_pca1_Final, summary(model_pca1)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_pca1_Final$Variable <- "pca1"

model_pca2 <- lm(pca2 ~ scale(Temperature) + I(scale(Temperature)^2) + scale(Aridity) + I(scale(Aridity)^2) + scale(Temperature)*scale(Aridity) + scale(Temperature)*I(scale(Aridity)^2) + I(scale(Temperature)^2)*scale(Aridity) + I(scale(Temperature)^2)*I(scale(Aridity)^2) + scale(Elevation) + scale(Forest_Age) + factor(Biome) + scale(Plotsize), data=DifCWM_Envars)
summary(model_pca2)
VarImp_pca2 <- calc.relimp(model_pca2, type = "lmg", rela = TRUE) #calculate relative importance scaled to 100 #Temp*-Temp2*-Aridity-Aridity2*: contributing >5%
VarImp_pca2 <- as.data.frame(VarImp_pca2@lmg)
VarImp_pca2_Final <- VarImp_pca2 %>% rename(VarImp=`VarImp_pca2@lmg`)
VarImp_pca2_Final <- cbind(VarImp_pca2_Final, summary(model_pca2)$coefficients[c(-1,-9,-10,-11,-12),])
VarImp_pca2_Final$Variable <- "pca2"

Final_models <- rbind(VarImp_Height_Final, VarImp_CrownDiameter_Final, VarImp_BarkThickness_Final, VarImp_WoodDensity_Final, VarImp_SLA_Final, VarImp_LeafN_Final, VarImp_LeafNP_Final, VarImp_StemConduitDiam_Final, VarImp_RootDepth_Final, VarImp_SeedMass_Final, VarImp_Gymnosperm_Final, VarImp_pca1_Final, VarImp_pca2_Final)

Final_models <- tibble::rownames_to_column(Final_models, "Term")

write_xlsx(Final_models, "Final_models_5-2024.xlsx") #Final_models.xlsx

#########################INTERACTIONS
###General model
Model_AT <- gam(Aridity ~ Temperature, data=DifCWM_Envars)
Data_AT <- with(DifCWM_Envars, data.frame(Temperature = seq(min(Temperature), max(Temperature), len=1000))) %>% mutate(Aridity = predict(Model_AT, newdata = (.), se = FALSE), Aridity_se = predict(Model_AT, newdata = (.), se = TRUE)$se) %>%
mutate(Aridity_upper = Aridity+1.96*Aridity_se, Aridity_lower = Aridity-1.96*Aridity_se)

dummy_dat <- with(DifCWM_Envars, data.frame(Temperature = seq(min(Temperature), max(Temperature), len=1000))) #Forest_AgeScaled=mean(Forest_AgeScaled, na.rm=T)

AI_cut <- quantile(DifCWM_Envars$Aridity, c(0.08, 0.988, 1), na.rm=T) #0.55, 0.988, 1 #0.08, 0.5, 0.98
AI_cut

all_dat <- data.frame()

for(i in 1:length(AI_cut)){
  all_dat <- all_dat %>% bind_rows(dummy_dat %>% mutate(Aridity = AI_cut[i]))}

###Graphs
Model_AridityTemp <- lm(Height  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(Height = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

Height_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=Height, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Height") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 10, y = 0, xend = 10, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(CrownDiameter  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(CrownDiameter = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

CrownDiameter_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=CrownDiameter, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ CrownDiameter") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 4, y = 0, xend = 4, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(BarkThickness  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(BarkThickness = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

BarkThickness_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=BarkThickness, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Bark Thickness") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 12, y = 0, xend = 12, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(WoodDensity  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(WoodDensity = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

WoodDensity_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=WoodDensity, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Wood Density") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 9, y = 0, xend = 9, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(SLA  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(SLA = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

SLA_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=SLA, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ SLA") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 6, y = 0, xend = 6, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(LeafN  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(LeafN = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

LeafN_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=LeafN, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ LeafN") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 5, y = 0, xend = 5, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(LeafNP  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(LeafNP = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

LeafNP_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=LeafNP, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Leaf NP") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 2, y = 0, xend = 2, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(StemConduitDiameter  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(StemConduitDiameter = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

StemConduitDiameter_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=StemConduitDiameter, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Stem Conduit Diam.") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 7, y = 0, xend = 7, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(RootDepth  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(RootDepth = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

RootDepth_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=RootDepth, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Root Depth") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 6, y = 0, xend = 6, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(SeedMass  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(SeedMass = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

SeedMass_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=SeedMass, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ Seed Mass") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 10, y = 0, xend = 10, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(pca1  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(pca1 = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

pca1_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=pca1, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ pca1") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 8, y = 0, xend = 8, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Model_AridityTemp <- lm(pca2  ~ Temperature * Aridity, data=DifCWM_Envars)
all_Temp <- all_dat %>% mutate(pca2 = predict(Model_AridityTemp, newdata = all_dat)) %>% as.data.frame()
all_Temp$Aridity <- factor(all_Temp$Aridity)

pca2_TempAridity <- ggplot(all_Temp, aes(x=Temperature, y=pca2, color=Aridity)) +
  geom_point() + ylim(c(-1, 1)) + 
  xlab("Temperature (°C)") + ylab("Δ pca2") +
  theme_classic()+ scale_colour_manual("Aridity Index", values=c("#fab302", "#9e7306", "#4a3501"), labels = c("Low (<0.7)", "Median (0.7-2)", "High (>2)"))+ #"#e600ff", "#8400ff", "#390061", "#390061"
  geom_hline(yintercept=0, color = "grey", size=1) +
  geom_segment(aes(x = 8, y = 0, xend = 8, yend = -Inf), size=0.5, linetype="dashed", colour="black") +
  theme(legend.position = "none",
        legend.text=element_text(size=12),
        legend.title=element_text(size=12, face="bold"),
        #legend.key.size = unit(3,"line"), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 14)) +
  guides(color = guide_legend(override.aes = list(size=3)))

Fig4C <- grid.arrange(CrownDiameter_TempAridity, Height_TempAridity, WoodDensity_TempAridity, StemConduitDiameter_TempAridity, BarkThickness_TempAridity, LeafN_TempAridity, LeafNP_TempAridity, SLA_TempAridity, RootDepth_TempAridity, SeedMass_TempAridity, pca1_TempAridity, pca2_TempAridity, nrow=4, top=textGrob("Trait differences correlated with interaction temperature & aridity", gp=gpar(col="black", fontsize=25, fontface="bold")), padding = unit(3,"line"))

```
